#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Minis × Shortcuts Playground —— 生成「学习记录」「学习周报」快捷指令草稿。
策略说明：所有动作序列化均依据 shortcuts-builder 技能库（toolkit v78）与黄金样例校准；
调整日期一律使用「静态时长 + WFQuantityFieldValue」，避免变量时长的未验证风险。
"""
import plistlib, uuid, pathlib, json

OUT = pathlib.Path("/var/minis/attachments/shortcut/drafts")
PROMPT_BLOCK = (
    "Shortcuts generated by Shortcuts Playground. May contain mistakes. "
    "Always check the shortcut's actions first.\n\n"
    "This shortcut was created via the following user prompt:\n\n"
    "> 构建基于「学习」专注模式的自动学习时间记录系统：『学习记录』负责开始/结束计时并写入文本文件；"
    "『学习周报』负责统计最近七个自然日（含今天）的学习时长。"
)

def U():
    return str(uuid.uuid4()).upper()

def u16len(s):
    return sum(2 if ord(c) > 0xFFFF else 1 for c in s)

def out_ref(uid, name, aggs=None):
    d = {"OutputName": name, "OutputUUID": uid, "Type": "ActionOutput"}
    if aggs:
        d["Aggrandizements"] = aggs
    return d

def var_ref(name):
    return {"Type": "Variable", "VariableName": name}

def attach(ref):
    return {"Value": ref, "WFSerializationType": "WFTextTokenAttachment"}

def wrap_input(ref):
    return {"Type": "Variable", "Variable": attach(ref)}

def tok(*parts):
    """parts: 字符串 或 变量引用dict（直接作为 attachmentsByRange 的值）"""
    buf, atts, pos = [], {}, 0
    for p in parts:
        if isinstance(p, str):
            buf.append(p)
            pos += u16len(p)
        else:
            atts["{%d, 1}" % pos] = p
            buf.append("\uFFFC")
            pos += 1
    return {"Value": {"string": "".join(buf), "attachmentsByRange": atts},
            "WFSerializationType": "WFTextTokenString"}

def C(text):
    return {"WFWorkflowActionIdentifier": "is.workflow.actions.comment",
            "WFWorkflowActionParameters": {"WFCommentActionText": text}}

def A(ident, params=None):
    return {"WFWorkflowActionIdentifier": ident,
            "WFWorkflowActionParameters": params if params is not None else {}}

def if_start(gid, cond, ref, s=None, n=None):
    p = {"GroupingIdentifier": gid, "WFControlFlowMode": 0, "WFCondition": cond,
         "WFInput": wrap_input(ref)}
    if s is not None:
        p["WFConditionalActionString"] = s
    if n is not None:
        p["WFNumberValue"] = n
    return A("is.workflow.actions.conditional", p)

def else_(gid):
    return A("is.workflow.actions.conditional",
             {"GroupingIdentifier": gid, "WFControlFlowMode": 1})

def endif(gid):
    return A("is.workflow.actions.conditional",
             {"GroupingIdentifier": gid, "WFControlFlowMode": 2, "UUID": U()})

def rep_start(gid, count):
    return A("is.workflow.actions.repeat.count",
             {"GroupingIdentifier": gid, "WFControlFlowMode": 0, "WFRepeatCount": count})

def rep_end(gid):
    return A("is.workflow.actions.repeat.count",
             {"GroupingIdentifier": gid, "WFControlFlowMode": 2, "UUID": U()})

def reach_start(gid, ref):
    return A("is.workflow.actions.repeat.each",
             {"GroupingIdentifier": gid, "WFControlFlowMode": 0,
              "WFInput": attach(ref), "UUID": U()})

def reach_end(gid):
    return A("is.workflow.actions.repeat.each",
             {"GroupingIdentifier": gid, "WFControlFlowMode": 2, "UUID": U()})

def fmt_date(uid, ref, pattern):
    return A("is.workflow.actions.format.date",
             {"UUID": uid, "WFDate": tok(ref), "WFDateFormatStyle": "Custom",
              "WFDateFormat": "Custom", "WFDateFormatString": pattern})

def setvar(uid, name, ref):
    return A("is.workflow.actions.setvariable",
             {"UUID": uid, "WFVariableName": name, "WFInput": attach(ref)})

def addvar(uid, name, ref):
    return A("is.workflow.actions.appendvariable",
             {"UUID": uid, "WFVariableName": name, "WFInput": attach(ref)})

def adjust(uid, ref, op, mag, unit="days", custom=None):
    p = {"UUID": uid, "WFAdjustOperation": op, "WFDate": tok(ref),
         "WFDuration": {"Value": {"Magnitude": float(mag), "Unit": unit},
                        "WFSerializationType": "WFQuantityFieldValue"}}
    if custom:
        p["CustomOutputName"] = custom
    return A("is.workflow.actions.adjustdate", p)

def number(uid, val):
    return A("is.workflow.actions.number",
             {"UUID": uid, "WFNumberActionNumber": str(val)})

def math(uid, ref, op, operand, custom=None):
    p = {"UUID": uid, "WFInput": attach(ref), "WFMathOperand": operand}
    if op:
        p["WFMathOperation"] = op
    if custom:
        p["CustomOutputName"] = custom
    return A("is.workflow.actions.math", p)

def fmt_num(uid, ref, places, custom):
    return A("is.workflow.actions.format.number",
             {"UUID": uid, "WFNumber": attach(ref),
              "WFNumberFormatDecimalPlaces": float(places),
              "CustomOutputName": custom})

def getfile(uid, path):
    return A("is.workflow.actions.documentpicker.open",
             {"UUID": uid, "WFFileErrorIfNotFound": False,
              "WFGetFilePath": path, "WFShowFilePicker": False})

def detect_text(uid, ref, custom):
    return A("is.workflow.actions.detect.text",
             {"UUID": uid, "WFInput": attach(ref), "CustomOutputName": custom})

def gettext(uid, text):
    return A("is.workflow.actions.gettext", {"UUID": uid, "WFTextActionText": text})

def savefile(ref, dest="StudyTracker/"):
    return A("is.workflow.actions.documentpicker.save",
             {"WFAskWhereToSave": False, "WFFileDestinationPath": dest,
              "WFSaveFileOverwrite": True, "WFInput": attach(ref)})

def setname(uid, ref, name):
    return A("is.workflow.actions.setitemname",
             {"UUID": uid, "WFInput": attach(ref), "WFName": name})

def exit_shortcut():
    return A("is.workflow.actions.exit", {})


def build_recorder():
    a = []
    a.append(C("学习记录 — 自动学习计时器。开启「学习」专注模式时记录开始时间；关闭时计算本次时长、追加到历史记录，"
               "并把状态标记为已结束。日常只需开启或关闭「学习」专注模式，不需要手动运行本快捷指令。"))
    a.append(C(PROMPT_BLOCK))
    a.append(C("判断当前专注模式（布线与用途）：\n"
               "- 获取当前专注模式，检查是否包含「学习」\n"
               "- 是 → 开始分支：记录开始时间\n"
               "- 否 → 结束分支：结算本次学习时长"))
    fu = U()
    a.append(A("is.workflow.actions.dnd.getfocus",
               {"UUID": fu, "CustomOutputName": "当前专注模式"}))
    a.append(C("分支判断：\n- 当前专注模式包含「学习」→ 执行开始分支\n- 否则 → 执行结束分支"))
    g_focus = U()
    a.append(if_start(g_focus, 99,
                      out_ref(fu, "当前专注模式",
                              [{"CoercionItemClass": "WFStringContentItem",
                                "Type": "WFCoercionVariableAggrandizement"}]),
                      s="学习"))

    # ===== 开始分支 =====
    a.append(C("开始分支：\n"
               "- 先读取 active.txt：若存有尚未结束的旧会话则保持原样、不覆盖\n"
               "- 读取当前时间并格式化，覆盖写入 active.txt"))
    f1 = U()
    a.append(getfile(f1, "StudyTracker/active.txt"))
    a.append(C("开始分支检查：\n- 读取现有记录文件\n- 有内容 → 进入未结束会话判断\n- 无内容 → 正常开始计时"))
    g1 = U()
    a.append(if_start(g1, 100, out_ref(f1, "File")))
    t1 = U()
    a.append(detect_text(t1, out_ref(f1, "File"), "现有内容"))
    a.append(C("旧会话保护（外层）：\n- 旧内容为空 → 视为无会话，正常写入\n- 旧内容非空 → 继续核对是否已结束"))
    g2a = U()
    a.append(if_start(g2a, 100, out_ref(t1, "现有内容")))
    a.append(C("旧会话保护（内层）：\n- 不含结束标记 → 存在未结束会话，保持原样并停止\n- 含结束标记 → 正常写入新的开始时间"))
    g2b = U()
    a.append(if_start(g2b, 999, out_ref(t1, "现有内容"), s="CLOSED"))
    a.append(exit_shortcut())
    a.append(endif(g2b))
    a.append(endif(g2a))
    a.append(endif(g1))
    d1 = U()
    a.append(A("is.workflow.actions.date", {"UUID": d1}))
    fd1 = U()
    a.append(fmt_date(fd1, out_ref(d1, "Date"), "yyyy-MM-dd HH:mm:ss"))
    sn1 = U()
    a.append(setname(sn1, out_ref(fd1, "Formatted Date"), "active.txt"))
    a.append(savefile(out_ref(sn1, "Renamed Item")))

    # ===== 结束分支 =====
    a.append(else_(g_focus))
    a.append(C("结束分支：\n"
               "- 读取 active.txt；不存在或已标记结束 → 直接停止，避免重复记录\n"
               "- 解析开始时间并计算时长；无效时长 → 停止\n"
               "- 追加一行记录，最后把 active.txt 标记为已结束"))
    f2 = U()
    a.append(getfile(f2, "StudyTracker/active.txt"))
    a.append(C("结算前检查：\n- 记录文件不存在 → 直接停止\n- 记录文件存在 → 继续结算"))
    g3 = U()
    a.append(if_start(g3, 101, out_ref(f2, "File")))
    a.append(exit_shortcut())
    a.append(endif(g3))
    t2 = U()
    a.append(detect_text(t2, out_ref(f2, "File"), "文件内容"))
    a.append(C("空内容保护：\n- 文件为空 → 无法结算，停止\n- 有内容 → 继续解析开始时间"))
    g3b = U()
    a.append(if_start(g3b, 101, out_ref(t2, "文件内容")))
    a.append(exit_shortcut())
    a.append(endif(g3b))
    a.append(C("重复结算保护：\n- 文件已含结束标记 → 已结算过，停止\n- 未含结束标记 → 进入时长计算"))
    g4 = U()
    a.append(if_start(g4, 99, out_ref(t2, "文件内容"), s="CLOSED"))
    a.append(exit_shortcut())
    a.append(endif(g4))
    dd1 = U()
    a.append(A("is.workflow.actions.detect.date",
               {"UUID": dd1, "WFInput": attach(out_ref(t2, "文件内容")),
                "CustomOutputName": "解析出的开始时间"}))
    sv1 = U()
    a.append(setvar(sv1, "开始时间", out_ref(dd1, "解析出的开始时间")))
    d2 = U()
    a.append(A("is.workflow.actions.date", {"UUID": d2}))
    sv2 = U()
    a.append(setvar(sv2, "结束时间", out_ref(d2, "Date")))
    gt1 = U()
    a.append(A("is.workflow.actions.gettimebetweendates",
               {"UUID": gt1,
                "WFTimeUntilFromDate": tok(var_ref("开始时间")),
                "WFInput": tok(var_ref("结束时间")),
                "WFTimeUntilUnit": "Seconds",
                "CustomOutputName": "本次时长"}))
    sv3 = U()
    a.append(setvar(sv3, "学习秒数", out_ref(gt1, "本次时长")))
    a.append(C("时长校验：\n- 秒数无效或 ≤ 0 → 停止，不记账\n- 秒数为正 → 生成记录行"))
    g5 = U()
    a.append(if_start(g5, 1, var_ref("学习秒数"), n="0"))
    a.append(exit_shortcut())
    a.append(endif(g5))
    fd2 = U()
    a.append(fmt_date(fd2, var_ref("开始时间"), "yyyy-MM-dd"))
    sv4 = U()
    a.append(setvar(sv4, "学习日期", out_ref(fd2, "Formatted Date")))
    fd3 = U()
    a.append(fmt_date(fd3, var_ref("开始时间"), "HH:mm"))
    sv5 = U()
    a.append(setvar(sv5, "开始时刻", out_ref(fd3, "Formatted Date")))
    fd4 = U()
    a.append(fmt_date(fd4, var_ref("结束时间"), "HH:mm"))
    sv6 = U()
    a.append(setvar(sv6, "结束时刻", out_ref(fd4, "Formatted Date")))
    fn1 = U()
    a.append(fmt_num(fn1, var_ref("学习秒数"), 0, "秒数文本"))
    tx1 = U()
    a.append(gettext(tx1, tok(var_ref("学习日期"), "|", var_ref("开始时刻"), "|",
                              var_ref("结束时刻"), "|", out_ref(fn1, "秒数文本"))))
    a.append(A("is.workflow.actions.file.append",
               {"WFFilePath": "StudyTracker/sessions.txt",
                "WFAppendFileWriteMode": "Append", "WFAppendOnNewLine": True,
                "WFInput": attach(out_ref(tx1, "Text"))}))
    tx2 = U()
    a.append(gettext(tx2, "CLOSED"))
    sn2 = U()
    a.append(setname(sn2, out_ref(tx2, "Text"), "active.txt"))
    a.append(savefile(out_ref(sn2, "Renamed Item")))
    a.append(endif(g_focus))
    return "学习记录", a


def build_weekly():
    a = []
    a.append(C("学习周报 — 统计最近七个自然日（含今天）的学习时长。只读取记录做统计，不会修改任何原始数据。"
               "随时运行查看即可，也可以把它加到主屏幕方便点开。"))
    a.append(C(PROMPT_BLOCK))
    a.append(C("读取记录：\n- 读取 sessions.txt；没有记录 → 提示后停止\n- 把全部记录拆分成逐行清单备用"))
    f1 = U()
    a.append(getfile(f1, "StudyTracker/sessions.txt"))
    a.append(C("文件检查：\n- 记录文件不存在 → 提示后停止\n- 记录文件存在 → 开始统计"))
    g0 = U()
    a.append(if_start(g0, 101, out_ref(f1, "File")))
    a.append(A("is.workflow.actions.showresult",
               {"Text": tok("暂时还没有学习记录——开启「学习」专注模式开始第一次学习吧！")}))
    a.append(exit_shortcut())
    a.append(endif(g0))
    t1 = U()
    a.append(detect_text(t1, out_ref(f1, "File"), "全部记录文本"))
    sv1 = U()
    a.append(setvar(sv1, "全部记录", out_ref(t1, "全部记录文本")))
    sp1 = U()
    a.append(A("is.workflow.actions.text.split",
               {"UUID": sp1, "text": tok(var_ref("全部记录")), "WFTextSeparator": "New Lines"}))
    sv2 = U()
    a.append(setvar(sv2, "记录列表", out_ref(sp1, "Split Text")))
    n1 = U()
    a.append(number(n1, 0))
    sv3 = U()
    a.append(setvar(sv3, "七天总秒数", out_ref(n1, "Number")))
    a.append(C("七天循环（外层）：\n"
               "- 从 6 天前开始，逐日推进到「今天」\n"
               "- 每天先取日期字符串，随后逐条统计并在末尾生成明细行\n"
               "- 同时把当天秒数累加进七天总秒数"))
    d1 = U()
    a.append(A("is.workflow.actions.date", {"UUID": d1}))
    ad1 = U()
    a.append(adjust(ad1, out_ref(d1, "Date"), "Subtract", 6, "days", custom="起始日期"))
    sv4 = U()
    a.append(setvar(sv4, "当前日期", out_ref(ad1, "起始日期")))
    a.append(C("七天循环开始：\n- 从 6 天前逐日推进到「今天」，共 7 天\n- 每天统计当天秒数、生成明细行\n- 每天结束时把「当前日期」推进 1 天"))
    gA = U()
    a.append(rep_start(gA, 7))
    fd1 = U()
    a.append(fmt_date(fd1, var_ref("当前日期"), "yyyy-MM-dd"))
    sv5 = U()
    a.append(setvar(sv5, "统计日期", out_ref(fd1, "Formatted Date")))
    n2 = U()
    a.append(number(n2, 0))
    sv6 = U()
    a.append(setvar(sv6, "当天秒数", out_ref(n2, "Number")))
    a.append(C("逐条统计（内层）：\n"
               "- 只处理包含当天日期的记录\n"
               "- 取该行最后一段的秒数并累加；当天没有记录则保持 0"))
    gB = U()
    a.append(reach_start(gB, var_ref("记录列表")))
    a.append(C("逐条判断：\n- 记录包含「统计日期」→ 拆分并累加秒数\n- 不包含该日期 → 跳过这条记录"))
    gC = U()
    a.append(if_start(gC, 99, var_ref("Repeat Item"), s=tok(var_ref("统计日期"))))
    sp2 = U()
    a.append(A("is.workflow.actions.text.split",
               {"UUID": sp2, "text": tok(var_ref("Repeat Item")),
                "WFTextSeparator": "Custom", "WFTextCustomSeparator": "|"}))
    gi1 = U()
    a.append(A("is.workflow.actions.getitemfromlist",
               {"UUID": gi1, "WFInput": attach(out_ref(sp2, "Split Text")),
                "WFItemSpecifier": "Last Item", "CustomOutputName": "最后一段"}))
    dn1 = U()
    a.append(A("is.workflow.actions.detect.number",
               {"UUID": dn1, "WFInput": attach(out_ref(gi1, "最后一段")),
                "CustomOutputName": "本次秒数"}))
    a.append(C("数值保护：\n- 取到有效秒数 → 累加进当天秒数\n- 无效或非数字 → 跳过该条，不计入"))
    gD = U()
    a.append(if_start(gD, 100, out_ref(dn1, "本次秒数")))
    m1 = U()
    a.append(math(m1, var_ref("当天秒数"), None, attach(out_ref(dn1, "本次秒数"))))
    sv7 = U()
    a.append(setvar(sv7, "当天秒数", out_ref(m1, "Calculation Result")))
    a.append(endif(gD))
    a.append(endif(gC))
    a.append(reach_end(gB))
    m2 = U()
    a.append(math(m2, var_ref("当天秒数"), "÷", 3600.0))
    fn1 = U()
    a.append(fmt_num(fn1, out_ref(m2, "Calculation Result"), 2, "当天小时数"))
    sv8 = U()
    a.append(setvar(sv8, "当天小时数", out_ref(fn1, "当天小时数")))
    m3 = U()
    a.append(math(m3, var_ref("七天总秒数"), None, attach(var_ref("当天秒数"))))
    sv9 = U()
    a.append(setvar(sv9, "七天总秒数", out_ref(m3, "Calculation Result")))
    tx1 = U()
    a.append(gettext(tx1, tok(var_ref("统计日期"), "：", var_ref("当天小时数"), " 小时")))
    av1 = U()
    a.append(addvar(av1, "周报明细", out_ref(tx1, "Text")))
    ad2 = U()
    a.append(adjust(ad2, var_ref("当前日期"), "Add", 1, "days", custom="下一天"))
    sv10 = U()
    a.append(setvar(sv10, "当前日期", out_ref(ad2, "下一天")))
    a.append(rep_end(gA))
    a.append(C("汇总展示：\n- 七天总时长换算成小时\n- 拼装每日明细与总时长，显示完整报告"))
    m4 = U()
    a.append(math(m4, var_ref("七天总秒数"), "÷", 3600.0))
    fn2 = U()
    a.append(fmt_num(fn2, out_ref(m4, "Calculation Result"), 2, "七天总小时数"))
    sv11 = U()
    a.append(setvar(sv11, "七天总小时数", out_ref(fn2, "七天总小时数")))
    cb1 = U()
    a.append(A("is.workflow.actions.text.combine",
               {"UUID": cb1, "text": attach(var_ref("周报明细")), "WFTextSeparator": "New Lines"}))
    sv12 = U()
    a.append(setvar(sv12, "周报正文", out_ref(cb1, "Combined Text")))
    tx2 = U()
    a.append(gettext(tx2, tok("📚 学习周报｜最近七天\n\n", var_ref("周报正文"),
                              "\n\n七天总学习时长：", var_ref("七天总小时数"), " 小时")))
    a.append(A("is.workflow.actions.showresult", {"Text": tok(out_ref(tx2, "Text"))}))
    return "学习周报", a


def root(name, actions, glyph, color):
    return {
        "WFWorkflowActions": actions,
        "WFWorkflowClientRelease": "26A0000a",
        "WFWorkflowClientVersion": "2700.0.4",
        "WFWorkflowHasOutputFallback": False,
        "WFWorkflowIcon": {"WFWorkflowIconGlyphNumber": glyph,
                           "WFWorkflowIconStartColor": color},
        "WFWorkflowImportQuestions": [],
        "WFWorkflowMinimumClientVersion": 900,
        "WFWorkflowMinimumClientVersionString": "900",
        "WFWorkflowName": name,
        "WFWorkflowOutputContentItemClasses": [],
        "WFWorkflowTypes": [],
    }


def audit(actions):
    errs = []
    ids = [x["WFWorkflowActionIdentifier"] for x in actions]
    if ids[0] != "is.workflow.actions.comment" or ids[1] != "is.workflow.actions.comment":
        errs.append("前两个动作必须都是注释")
    n = len(actions)
    nc = sum(1 for i in ids if i == "is.workflow.actions.comment")
    need = 2 if n < 8 else 3 if n < 16 else 4 if n < 24 else 5
    if nc < need:
        errs.append(f"注释数量不足: {nc} < {need}")
    uuids = []
    for x in actions:
        p = x["WFWorkflowActionParameters"]
        if isinstance(p, dict) and p.get("UUID"):
            uuids.append(p["UUID"])
    if len(set(uuids)) != len(uuids):
        errs.append("UUID 重复")
    known = set(uuids)

    def walk(o):
        if isinstance(o, dict):
            if o.get("Type") == "ActionOutput" and "OutputUUID" in o:
                if o["OutputUUID"] not in known:
                    errs.append(f"未知 OutputUUID: {str(o['OutputUUID'])[:8]}")
            if o.get("Type") == "Variable" and "VariableName" not in o and "Variable" not in o:
                errs.append("Variable 引用缺少名称")
            for v in o.values():
                walk(v)
        elif isinstance(o, list):
            for v in o:
                walk(v)

    stack = []
    for x in actions:
        p = x["WFWorkflowActionParameters"]
        gi = (p or {}).get("GroupingIdentifier")
        mode = (p or {}).get("WFControlFlowMode")
        if gi and isinstance(mode, int):
            if mode == 0:
                stack.append(gi)
            elif mode == 2:
                if not stack or stack[-1] != gi:
                    errs.append(f"控制流不配对: {gi[:8]}")
                else:
                    stack.pop()
        walk(x)
    if stack:
        errs.append("有未闭合的控制流块")
    return errs


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, builder, glyph, color in [
        ("study-recorder", build_recorder, 59712, 463140863),
        ("study-weekly", build_weekly, 59662, 431817727),
    ]:
        disp, actions = builder()
        errs = audit(actions)
        pl = root(disp, actions, glyph, color)
        path = OUT / f"{name}.xml"
        with open(path, "wb") as fh:
            plistlib.dump(pl, fh, fmt=plistlib.FMT_XML, sort_keys=False)
        print(json.dumps({"name": name, "display": disp, "actions": len(actions),
                          "comments": sum(1 for x in actions if x["WFWorkflowActionIdentifier"] == "is.workflow.actions.comment"),
                          "audit_errors": errs, "path": str(path),
                          "bytes": path.stat().st_size}, ensure_ascii=False))
    print("done")


if __name__ == "__main__":
    main()
